"""emit/versions.py — year → Docusaurus version mapping, carry-forward, manifests."""

import json
from pathlib import Path

from drive_sync.emit.format import emit_stale_banner
from drive_sync.emit.versions import (
    plan_versions,
    versioned_sidebars_path,
    versions_json_path,
    write_version_manifests,
)
from drive_sync.fetch import ContentTree, SlugFiles

OLD, NEW = "2024-2025", "2025-2026"


def _tree(*specs: tuple[str, str, str]) -> ContentTree:
    """specs are (kind, year, slug)."""
    tree = ContentTree()
    for kind, year, slug in specs:
        tree.add(SlugFiles(slug=slug, kind=kind, year=year))  # type: ignore[arg-type]
    return tree


def test_each_year_becomes_a_version() -> None:
    plan = plan_versions(_tree(("university", OLD, "aub"), ("university", NEW, "aub")))
    assert plan.years_by_plugin["universities"] == [NEW, OLD]
    assert {(e.year, e.files.slug) for e in plan.entries} == {(OLD, "aub"), (NEW, "aub")}
    assert all(e.stale_from is None for e in plan.entries)


def test_missing_slug_is_carried_forward_and_marked_stale() -> None:
    """aub skips the new year; lau only exists in the new year."""
    plan = plan_versions(
        _tree(
            ("university", OLD, "aub"),
            ("university", NEW, "lau"),
        )
    )
    by_year: dict[str, dict[str, object]] = {}
    for e in plan.entries:
        by_year.setdefault(e.year, {})[e.files.slug] = e.stale_from

    # The old version shows only what existed then.
    assert by_year[OLD] == {"aub": None}
    # The new version keeps aub alive, flagged as carried forward.
    assert by_year[NEW] == {"aub": OLD, "lau": None}


def test_carry_forward_does_not_leak_backwards() -> None:
    """A slug added in the new year must not appear in an older version."""
    plan = plan_versions(_tree(("university", OLD, "aub"), ("university", NEW, "elte")))
    old_slugs = {e.files.slug for e in plan.entries if e.year == OLD}
    assert old_slugs == {"aub"}


def test_output_paths_match_the_docusaurus_contract() -> None:
    plan = plan_versions(_tree(("university", NEW, "aub"), ("scholarship", NEW, "life")))
    paths = {(e.files.slug, loc): e.output_path(loc) for e in plan.entries for loc in ("en", "ar")}
    assert paths[("aub", "en")] == f"universities_versioned_docs/version-{NEW}/aub.mdx"
    assert paths[("aub", "ar")] == (
        f"i18n/ar/docusaurus-plugin-content-docs-universities/version-{NEW}/aub.mdx"
    )
    assert paths[("life", "en")] == f"scholarships_versioned_docs/version-{NEW}/life.mdx"
    assert paths[("life", "ar")] == (
        f"i18n/ar/docusaurus-plugin-content-docs-scholarships/version-{NEW}/life.mdx"
    )


def test_only_year_filters_pages_but_not_manifests() -> None:
    """`--year` is a dev filter; the version list must stay complete."""
    tree = _tree(("university", OLD, "aub"), ("university", NEW, "aub"))
    plan = plan_versions(tree, only_year=NEW)
    assert {e.year for e in plan.entries} == {NEW}
    assert plan.years_by_plugin["universities"] == [NEW, OLD]


def test_manifests_are_written(tmp_path: Path) -> None:
    plan = plan_versions(_tree(("university", OLD, "aub"), ("university", NEW, "aub")))
    write_version_manifests(plan, str(tmp_path))

    versions = json.loads((tmp_path / versions_json_path("universities")).read_text())
    assert versions == [NEW, OLD], "newest first — Docusaurus takes versions[0] as lastVersion"

    sidebar = json.loads((tmp_path / versioned_sidebars_path("universities", NEW)).read_text())
    assert sidebar == {"universitiesSidebar": [{"type": "autogenerated", "dirName": "."}]}

    label = json.loads(
        (tmp_path / f"i18n/ar/docusaurus-plugin-content-docs-universities/version-{NEW}.json").read_text()
    )
    assert label["version.label"]["message"] == NEW


def test_stale_banner_is_localized_and_names_both_years() -> None:
    en = emit_stale_banner("en", NEW, OLD)
    assert en.startswith(":::warning[")
    assert NEW in en and OLD in en

    ar = emit_stale_banner("ar", NEW, OLD)
    assert NEW in ar and OLD in ar
    assert any("؀" <= ch <= "ۿ" for ch in ar), "Arabic banner must be in Arabic"
